# Generated by Django 3.2.9 on 2021-11-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "noticia",
            },
        ),
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "pessoa",
            },
        ),
    ]
